Differentiate between stable/experimental languages in API and CLI
UAVCAN/nunavut pull request #177
Opened 2020-12-23 18:34 UTC by edwinbalani

A second approach to denoting 'experimental' languages (i.e. anything that's not C or Python for v1.0).

Controversially, I've chosen for the CLI to default to supplying `include_experimental_languages` as False when creating a LanguageContext, although in `LanguageContext.__init__` itself the default is `True`.  This would mean that most of the test code (and any Pythonic users of nunavut rather than CLI users) will have experimental languages available by default -- let me know how you feel about this.  My main motivations for that choice are that the bulk of the test code, which uses C++ and JSON outputs, can be left intact this way, and that the original issue #172 seems concerned mainly with CLI users.

@thirtytwobits please correct me if wrong - is Python stable, or is it just C right now?

Resolves #172.
Closes #173 by obsolence.

2020-12-26 01:06 UTC, edwinbalani commented
Only failing check now is a lint:

```
src/nunavut/lang/__init__.py:427:5: C901 'LanguageContext.__init__' is too complex (12)
    def __init__(self,
    ^
1     C901 'LanguageContext.__init__' is too complex (12)
```

Indicates too many branches... I'll see whether I can make things a bit less 🎄-ish

2020-12-28 05:10 UTC, thirtytwobits requested changes
We just need to update version.py with a new, minor revision. Can you do that and close your other PR and I'll accept and merge. Thanks for doing this!

2020-12-29 16:34 UTC, edwinbalani commented
> We just need to update version.py with a new, minor revision. Can you do that and close your other PR and I'll accept and merge. Thanks for doing this!

Great - no worries, I'm glad I could get one of the v1.0 tasks done!

By minor revision, I'll assume you mean the 'z' part of 'x.y.z'.  Commit incoming...

2020-12-29 16:40 UTC, edwinbalani commented
On second thoughts, I trust that you meant the 'y', since this is a more significant change in program behaviour than what warrants a patch rev (_and_ especially since we're technically still in v0, it's probably best placed in a minor revision rather than a major).

2020-12-29 23:43 UTC, thirtytwobits approved these changes

2020-12-29 23:43 UTC, merged